-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 13:56:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ejercicio4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ejercicio4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejercicio4` DEFAULT CHARACTER SET utf8 ;
USE `ejercicio4` ;

-- -----------------------------------------------------
-- Table `ejercicio4`.`tablita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejercicio4`.`tablita` (
  `idtablita` INT NOT NULL,
  `fecha` DATE NULL,
  `textogrande` VARCHAR(45) NULL,
  `tablitacol` LONGTEXT NULL,
  `numeroentero` INT NULL,
  `decimal` DECIMAL NULL,
  PRIMARY KEY (`idtablita`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
