USE discography_db;
INSERT INTO discography_db.album VALUES
(NULL, 'MASTER OF PUPPETS', '1986-03-03'),
(NULL, 'THE MOUNTAIN', '2013-09-02'),
(NULL, 'IN THE COURT OF THE CRIMSON KING', '1969-10-10'),
(NULL, 'HOMEY', '2017-06-16'),
(NULL, 'REVOLVER', '1966-08-05'),
(NULL, 'BACK IN BLACK', '1980-07-25'),
(NULL, 'LIFT YOUR SKINNY FISTS LIKE ANTENNAS TO HEAVEN', '2000-10-09'),
(NULL, 'FUTURE NOSTALGIA', '2020-03-27'),
(NULL, 'THE JOY OF MOTION', '2014-03-24'),
(NULL, '¿LA CALLE ES TUYA?', '2004-03-03');

INSERT INTO discography_db.artist VALUES
(NULL, 'METALLICA'),
(NULL, 'HAKEN'),
(NULL, 'KING CRIMSON'),
(NULL, 'CHON'),
(NULL, 'THE BEATLES'),
(NULL, 'AC/DC'),
(NULL, 'GODSPEED YOU! BLACK EMPEROR'),
(NULL, 'DUA LIPA'),
(NULL, 'ANIMALS AS LEADERS'),
(NULL, 'ESTOPA');

INSERT INTO discography_db.genre VALUES
(NULL, 'THRASH METAL'),
(NULL, 'PROGRESSIVE METAL'),
(NULL, 'PROGRESSIVE ROCK'),
(NULL, 'MATH ROCK'),
(NULL, 'ROCK'),
(NULL, 'HARD ROCK'),
(NULL, 'POST-ROCK'),
(NULL, 'POP'),
(NULL, 'DJENT'),
(NULL, 'RUMBA');

SELECT * FROM discography_db.album;