DROP DATABASE IF EXISTS discography_db;
CREATE DATABASE IF NOT EXISTS discography_db;
USE discography_db;

CREATE TABLE IF NOT EXISTS Genre  (
	idGenre INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Genre VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS Album  (
	idAlbum INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    albumName VARCHAR(255) NOT NULL,
    datReleased DATETIME
);
CREATE TABLE IF NOT EXISTS Artist  (
	idArtist INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    artistName VARCHAR(255) NOT NULL
);

DESCRIBE discography_db.Album;